function FourMicCheckForDoneCalibration(app)
% Copyright (C) Jose M. Requena Plens 
% joreple@upv.es - jmrplens.github.io

if ~isempty(app.ExtVar.ImpedanceTubeFourMic.OutputI) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.OutputII2) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.OutputII3) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.OutputII4) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic1I) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic2I) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic3I) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic4I) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic1II2) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic1II3) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic1II4) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic2II) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic3II) && ...
        ~isempty(app.ExtVar.ImpedanceTubeFourMic.Mic4II)
    
    app.ExtUI.FourMicTubeCalibrationDoneButton.Enable = 'on';
    app.ExtVar.ImpedanceTubeFourMic.Calibrated = true;
    app.ExtUI.PanelTubeFourMicRightInfoTubeCalLabel.Text = 'Yes';
else
    app.ExtUI.FourMicTubeCalibrationDoneButton.Enable = 'off';
    app.ExtVar.ImpedanceTubeFourMic.Calibrated = false;
    app.ExtUI.PanelTubeFourMicRightInfoTubeCalLabel.Text = 'No';
end

